<form method="post">
    <hr>
    <p>Add new employee below. Please be careful of codes.</p>

    <label for="code">Code</label>
    <input name="code" type="text" id="code">
    <br>
    <label for="fullName">Full name</label>
    <input name="fullName" type="text" id="fullName">
    <br>
    <label for="position">Position</label>
    <input name="position" type="text" id="position">
    <br>
    <label for="salary">Salary</label>
    <input name="salary" type="text" id="salary">
    <br>
    <label for="childrenAmount">Amount of children</label>
    <input name="childrenAmount" type="text" id="childrenAmount">
    <br>
    <label for="workExperience">Work experience</label>
    <input name="workExperience" type="text" id="workExperience">
    <br />
    <br />
    <button type="submit">Add new employee</button>
</form>

