<?php
/* var array $financeDepartments */
$financeDepartments;
?>
<table border="1">
    <tr>
        <th>Code</th>
        <th>Full name</th>
        <th>Position</th>
        <th>Salary, $</th>
        <th>Amount of children</th>
        <th>Work experience, yrs</th>
    </tr>
    <?php foreach ($financeDepartments as $financeDepartment): ?>
    <tr>
        <td><?= $financeDepartment['code'];?></td>
        <td><?= $financeDepartment['fullName'];?></td>
        <td><?= $financeDepartment['position'];?></td>
        <td><?= $financeDepartment['salary'];?></td>
        <td><?= $financeDepartment['childrenAmount'];?></td>
        <td><?= $financeDepartment['workExperience'];?></td>
    </tr>
    <?php endforeach;?>
</table>
