<?php
/* var array $financeDepartments */
$subjectsList;
?>
<table border="1">
    <tr>
        <th>Id</th>
        <th>Subject name</th>
        <th>Teacher</th>
        <th>Amount of points</th>
    </tr>
    <?php foreach ($subjectsList as $subject): ?>
        <tr>
            <td><a href="index.php?id=<?= $subject['id']; ?>"><?= $subject['id']; ?></a></td>
            <td><?= $subject['name'];?></td>
            <td><?= $subject['teacher'];?></td>
            <td><?= $subject['pointsAmount'];?></td>
        </tr>
    <?php endforeach;?>
</table>