<form method="post">
    <hr>
    <p>Form for adding subjects to the table</p>
    <label for="id">Id</label>
    <input name="id" type="text" id="id">
    <br>
    <label for="name">Subject name</label>
    <input name="name" type="text" id="name">
    <br>
    <label for="teacher">Teacher</label>
    <input name="teacher" type="text" id="teacher">
    <br>
    <label for="pointsAmount">Amount of points</label>
    <input name="pointsAmount" type="text" id="pointsAmount">
    <br>
    <hr>
    <button type="submit">Add new employee</button>
</form>